# my global config
global:
  scrape_interval:     15s # 15초마다 매트릭 수
  evaluation_interval: 15s # 15초마다 규칙 평가
  # scrape_timeout is set to the global default (10s).

# 알림관리 설정
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

#  규칙을 로딩하고 'evalution_interval' 설정에 따라 정기적으로 평가
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 매트릭을 수집할 엔드포인트
# 여기서  Prometheus는 서버 자신을 가리킨다.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path의 기본경로는 ' /metrics'
    # scheme의 기본값은 'http'이다.

    static_configs:
            - targets: ['localhost:9100']
#	     - targets: ['10.0.2.55:9100']

  - job_name: 'WEB'
    static_configs:
            - targets: ['13.124.111.234:9101']
              
  - job_name: 'WAS'
    static_configs:
            - targets: ['13.124.111.234:9102']
 

